version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Compile
          command: |
            npm run build
            npm run lint
      - run:
          name: Test
          command: npm test
      - run:
          name: Publish
          command: npm test
  publish:
    docker:
          - image: circleci/node:8.12.0
    steps:
      - run:
        name: Stat
        command: stat lib
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
