version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Compile
          command: npm run build
      - run:
          name: Test
          command: npm test
workflows:
  version: 2
   jobs:
      - build
