version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "15:97:81:6b:69:3c:a2:83:a9:1c:ac:11:c0:9d:0f:ec"
      - checkout
      - run:
          name: Install
          command: npm install
      - run:
          name: Compile
          command: |
            npm run build
            npm run lint
      - run:
          name: Test
          command: npm test
      - run:
          name: Publish
          command: |
            git config --global user.email "$GIT_AUTHOR_EMAIL"
            git config --global user.name "$GIT_AUTHOR_NAME"
            npm run cd
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
